name: docker

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/metadata-action@v5
        id: a
        with:
          images: ghcr.io/mac2000/a

      - name: a
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: a
          tags: ${{ steps.a.outputs.tags }}
          labels: ${{ steps.a.outputs.labels }}

      - uses: docker/metadata-action@v5
        id: b
        with:
          images: ghcr.io/mac2000/b

      - name: b
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: b
          tags: ${{ steps.a.outputs.tags }}
          labels: ${{ steps.a.outputs.labels }}
